### Sequencing method type specific HN-score calculation method

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import csv

%matplotlib inline

plt.style.use('ggplot')

### Using the HN-ratio table

In [2]:
df = pd.read_csv("../source/HN-ratio_human_All.csv", sep=",")
df.head()

,GeneName,SRR8392699,SRR8392700,SRR8392703,SRR8392704,SRR10129832,SRR9029562,SRR9029564,SRR9029566,SRR3309259,...,SRR9257642,SRR9257643,SRR9257644,SRR9257645,SRR12801712,SRR12801713,SRR12801714,SRR11067753,SRR11067754,SRR11067755
0,A1BG,0.937577,0.905060,1.173431,0.951361,1.616084,1.587653,0.839417,0.707164,0.688915,...,0.150518,3.972351,1.388637,0.267622,1.000000,1.0,1.000000,1.000000,1.000000,0.497684
1,A1CF,1.274827,1.000000,1.000000,1.000000,1.578923,1.121376,1.125679,1.256608,0.867105,...,1.000000,1.000000,1.000000,1.000000,0.939182,1.0,1.052121,1.029972,1.000000,1.000000
2,A2M,0.954195,1.510970,1.340899,0.800410,2.867888,0.271588,1.027820,0.628021,0.646622,...,1.000000,4.285260,1.000000,1.000000,1.000000,1.0,1.000000,0.875078,2.271058,1.530530
3,A2ML1,1.078959,0.649897,0.789869,1.665942,2.674006,8.028230,3.515341,9.282938,0.929338,...,1.000000,0.795947,1.000000,1.000000,1.000000,1.0,1.000000,2.026651,1.000000,1.000000
4,A3GALT2,1.000000,1.000000,1.000000,1.000000,0.924578,1.000000,1.000000,0.468382,0.600246,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000

In [3]:
# set index 
df1=df.set_index('GeneName')
df1.head()

,SRR8392699,SRR8392700,SRR8392703,SRR8392704,SRR10129832,SRR9029562,SRR9029564,SRR9029566,SRR3309259,SRR3309260,...,SRR9257642,SRR9257643,SRR9257644,SRR9257645,SRR12801712,SRR12801713,SRR12801714,SRR11067753,SRR11067754,SRR11067755
GeneName,,,,,,,,,,,,,,,,,,,,,
A1BG,0.937577,0.905060,1.173431,0.951361,1.616084,1.587653,0.839417,0.707164,0.688915,0.807707,...,0.150518,3.972351,1.388637,0.267622,1.000000,1.0,1.000000,1.000000,1.000000,0.497684
A1CF,1.274827,1.000000,1.000000,1.000000,1.578923,1.121376,1.125679,1.256608,0.867105,0.542718,...,1.000000,1.000000,1.000000,1.000000,0.939182,1.0,1.052121,1.029972,1.000000,1.000000
A2M,0.954195,1.510970,1.340899,0.800410,2.867888,0.271588,1.027820,0.628021,0.646622,1.000000,...,1.000000,4.285260,1.000000,1.000000,1.000000,1.0,1.000000,0.875078,2.271058,1.530530
A2ML1,1.078959,0.649897,0.789869,1.665942,2.674006,8.028230,3.515341,9.282938,0.929338,0.266727,...,1.000000,0.795947,1.000000,1.000000,1.000000,1.0,1.000000,2.026651,1.000000,1.000000
A3GALT2,1.000000,1.000000,1.000000,1.000000,0.924578,1.000000,1.000000,0.468382,0.600246,0.241123,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000

### Store SRR number data and sample data as a dictionary data type

In [4]:
with open("../source/human-sequencing-method.csv", encoding="utf-8-sig") as csvfile:   # create coresponding CSV file 
    f = csv.DictReader(csvfile)
    sequencing_type = [row for row in f]
    print(sequencing_type)

[{'SRR8392699': 'RNA-seq', 'SRR8392700': 'RNA-seq', 'SRR8392703': 'RNA-seq', 'SRR8392704': 'RNA-seq', 'SRR8392707': 'Ribo-seq', 'SRR8392708': 'Ribo-seq', 'SRR8392711': 'Ribo-seq', 'SRR8392712': 'Ribo-seq', 'SRR2522096': 'RNA-seq', 'SRR2522099': 'RNA-seq', 'SRR2522102': 'RNA-seq', 'SRR10129832': 'RNA-seq', 'SRR13436541': 'RNA-seq', 'SRR13436542': 'RNA-seq', 'SRR13436543': 'RNA-seq', 'SRR7309387': 'RNA-seq', 'SRR9029562': 'RNA-seq', 'SRR9029564': 'RNA-seq', 'SRR9029566': 'RNA-seq', 'SRR9029563': 'MeRIP-seq', 'SRR9029565': 'MeRIP-seq', 'SRR9029567': 'MeRIP-seq', 'SRR3309259': 'RNA-seq', 'SRR3309260': 'RNA-seq', 'SRR3309261': 'RNA-seq', 'SRR7241962': 'RNA-seq', 'SRR7241963': 'RNA-seq', 'SRR7241964': 'RNA-seq', 'SRR7241965': 'RNA-seq', 'SRR7241966': 'RNA-seq', 'SRR7241967': 'RNA-seq', 'SRR7241968': 'RNA-seq', 'SRR7241969': 'RNA-seq', 'SRR7241970': 'RNA-seq', 'SRR10908166': 'RNA-seq', 'SRR10908167': 'RNA-seq', 'SRR10908168': 'RNA-seq', 'SRR10908163': 'RNA-seq', 'SRR10908164': 'RNA-seq', 'SRR10908165': 'RNA-seq', 'SRR648668': 'Ribo-seq', 'SRR648670': 'Ribo-seq', 'SRR15177493': 'm6Am-seq', 'SRR15177494': 'm6Am-seq', 'SRR15177495': 'm6Am-seq', 'SRR15177496': 'm6Am-seq', 'SRR15177497': 'm6Am-seq', 'SRR15177498': 'm6Am-seq', 'SRR15177499': 'm6Am-seq', 'SRR18302238': 'RNA-seq', 'SRR18302239': 'RNA-seq', 'SRR18302240': 'RNA-seq', 'SRR18302251': 'RNA-seq', 'SRR18302252': 'RNA-seq', 'SRR18302254': 'RNA-seq', 'SRR18302262': 'RNA-seq', 'SRR18302263': 'RNA-seq', 'SRR18302264': 'RNA-seq', 'SRR18302274': 'RNA-seq', 'SRR18302275': 'RNA-seq', 'SRR18302276': 'RNA-seq', 'SRR7359773': 'RNA-seq', 'SRR7359774': 'RNA-seq', 'SRR7359775': 'RNA-seq', 'SRR7359665': 'RNA-seq', 'SRR7359666': 'RNA-seq', 'SRR7359667': 'RNA-seq', 'SRR7359701': 'RNA-seq', 'SRR7359702': 'RNA-seq', 'SRR7359703': 'RNA-seq', 'SRR7359737': 'RNA-seq', 'SRR7359738': 'RNA-seq', 'SRR7359739': 'RNA-seq', 'SRR7359761': 'RNA-seq', 'SRR7359762': 'RNA-seq', 'SRR7359763': 'RNA-seq', 'SRR7359785': 'RNA-seq', 'SRR7359786': 'RNA-seq', 'SRR7359787': 'RNA-seq', 'SRR7359797': 'RNA-seq', 'SRR7359798': 'RNA-seq', 'SRR7359799': 'RNA-seq', 'SRR7359677': 'RNA-seq', 'SRR7359678': 'RNA-seq', 'SRR7359679': 'RNA-seq', 'SRR7359689': 'RNA-seq', 'SRR7359690': 'RNA-seq', 'SRR7359691': 'RNA-seq', 'SRR7359713': 'RNA-seq', 'SRR7359714': 'RNA-seq', 'SRR7359715': 'RNA-seq', 'SRR7359725': 'RNA-seq', 'SRR7359726': 'RNA-seq', 'SRR7359727': 'RNA-seq', 'SRR7359749': 'RNA-seq', 'SRR7359750': 'RNA-seq', 'SRR7359751': 'RNA-seq', 'SRR12926169': 'RNA-seq', 'SRR12926170': 'RNA-seq', 'SRR12926171': 'RNA-seq', 'SRR12926172': 'RNA-seq', 'SRR12926185': 'RNA-seq', 'SRR12926186': 'RNA-seq', 'SRR12926187': 'RNA-seq', 'SRR12926188': 'RNA-seq', 'SRR12926161': 'RNA-seq', 'SRR12926162': 'RNA-seq', 'SRR12926163': 'RNA-seq', 'SRR12926164': 'RNA-seq', 'SRR12926177': 'RNA-seq', 'SRR12926178': 'RNA-seq', 'SRR12926179': 'RNA-seq', 'SRR12926180': 'RNA-seq', 'SRR19077081': 'PRO-seq', 'SRR19077089': 'PRO-seq', 'SRR19077082': 'PRO-seq', 'SRR19077090': 'PRO-seq', 'SRR19077085': 'PRO-seq', 'SRR19077093': 'PRO-seq', 'SRR19077086': 'PRO-seq', 'SRR19077094': 'PRO-seq', 'SRR12801710': 'SLAM-seq', 'SRR12801711': 'SLAM-seq', 'SRR11067756': 'SLAM-seq', 'SRR11067757': 'SLAM-seq', 'SRR11067758': 'SLAM-seq', 'SRR12801712': 'SLAM-seq', 'SRR12801713': 'SLAM-seq', 'SRR12801714': 'SLAM-seq', 'SRR11067753': 'SLAM-seq', 'SRR11067754': 'SLAM-seq', 'SRR11067755': 'SLAM-seq', 'SRR16555321': 'RNA-seq', 'SRR16555322': 'RNA-seq', 'SRR16555315': 'RNA-seq', 'SRR16555316': 'RNA-seq', 'SRR16555317': 'RNA-seq', 'SRR16555318': 'RNA-seq', 'SRR17038864': 'RNA-seq', 'SRR17038865': 'RNA-seq', 'SRR17038866': 'RNA-seq', 'SRR11817840': 'RNA-seq', 'SRR11817841': 'RNA-seq', 'SRR11817842': 'RNA-seq', 'SRR11817843': 'RNA-seq', 'SRR11817844': 'RNA-seq', 'SRR11817845': 'RNA-seq', 'SRR11817852': 'RNA-seq', 'SRR11817853': 'RNA-seq', 'SRR11817854': 'RNA-seq', 'SRR11817855': 'RNA-seq', 'SRR11817856': 'RNA-seq', 'SRR11817857': 'RNA-seq', 'SRR9257619': 'RNA-seq', 'SRR9257620': 'RNA-seq', 'SRR9257621': 'RNA-seq', 'SRR9257622': 'RNA-seq', 'SRR9257623': 'RNA-seq', 'SRR9257624': 'RNA-seq', 'SRR9257625': 'RNA-seq', 'SRR9257626': 'RNA-seq', 'SRR9257627': 'RNA-seq', 'SRR9257637': 'RNA-seq', 'SRR9257638': 'RNA-seq', 'SRR9257639': 'RNA-seq', 'SRR9257640': 'RNA-seq', 'SRR9257641': 'RNA-seq', 'SRR9257642': 'RNA-seq', 'SRR9257643': 'RNA-seq', 'SRR9257644': 'RNA-seq', 'SRR9257645': 'RNA-seq', 'SRR11684069': 'RNA-seq', 'SRR11684070': 'RNA-seq', 'SRR11684071': 'RNA-seq', 'SRR11684072': 'RNA-seq', 'SRR11684073': 'RNA-seq', 'SRR11684074': 'RNA-seq', 'SRR10761036': 'RNA-seq', 'SRR10761037': 'RNA-seq', 'SRR10761038': 'RNA-seq', 'SRR1061343': 'RNA-seq', 'SRR1061344': 'RNA-seq', 'SRR11195423': 'RNA-seq', 'SRR11195425': 'RNA-seq', 'SRR11195422': 'RNA-seq', 'SRR11195424': 'RNA-seq', 'SRR11195426': 'RNA-seq', 'SRR11195427': 'RNA-seq', 'SRR11195428': 'RNA-seq', 'SRR11195429': 'RNA-seq', 'SRR11195431': 'RNA-seq', 'SRR11195433': 'RNA-seq', 'SRR11195430': 'RNA-seq', 'SRR11195432': 'RNA-seq', 'SRR8334015': 'TT-seq', 'SRR8334016': 'TT-seq', 'SRR8334017': 'TT-seq', 'SRR8334018': 'TT-seq', 'SRR8334021': 'RNA-seq', 'SRR8334022': 'RNA-seq', 'SRR8334023': 'RNA-seq', 'SRR8334024': 'RNA-seq', 'SRR8334027': 'mNET-seq', 'SRR8334028': 'mNET-seq', 'SRR8334029': 'mNET-seq', 'SRR8334030': 'mNET-seq', 'SRR8334035': 'TT-seq', 'SRR8334036': 'TT-seq', 'SRR8334037': 'TT-seq', 'SRR8334038': 'TT-seq', 'SRR10953094': 'RNA-seq', 'SRR10953095': 'RNA-seq', 'SRR10953096': 'RNA-seq', 'SRR10953097': 'RNA-seq', 'SRR10953098': 'RNA-seq', 'SRR8669175': 'PRO-seq', 'SRR8669176': 'PRO-seq', 'SRR8669177': 'PRO-seq', 'SRR8669167': 'PRO-seq', 'SRR8669168': 'PRO-seq', 'SRR8669169': 'PRO-seq', 'SRR8669170': 'PRO-seq', 'SRR8669171': 'PRO-seq', 'SRR12267715': 'PRO-seq', 'SRR12267716': 'PRO-seq', 'SRR12267717': 'PRO-seq', 'SRR12267718': 'PRO-seq', 'SRR12267719': 'PRO-seq', 'SRR12267720': 'PRO-seq', 'SRR12267721': 'PRO-seq', 'SRR12267722': 'PRO-seq', 'SRR13436390': 'RNA-seq', 'SRR13436391': 'RNA-seq', 'SRR13436392': 'RNA-seq', 'SRR13436393': 'RNA-seq', 'SRR13436394': 'RNA-seq', 'SRR13436395': 'RNA-seq', 'SRR13436396': 'RNA-seq', 'SRR13436397': 'RNA-seq', 'SRR13436398': 'RNA-seq', 'SRR13436399': 'RNA-seq', 'SRR13436400': 'RNA-seq', 'SRR13436401': 'RNA-seq', 'SRR13510258': 'TTchem-seq', 'SRR13510259': 'TTchem-seq', 'SRR13510260': 'TTchem-seq', 'SRR13510262': 'TTchem-seq', 'SRR13510263': 'TTchem-seq', 'SRR13510264': 'TTchem-seq', 'SRR13510285': 'TTchem-seq', 'SRR13510286': 'TTchem-seq', 'SRR13510287': 'TTchem-seq', 'SRR13510288': 'TTchem-seq', 'SRR13510289': 'TTchem-seq', 'SRR13510290': 'TTchem-seq', 'SRR13510291': 'TTchem-seq', 'SRR13510292': 'TTchem-seq', 'SRR13510293': 'TTchem-seq', 'SRR13510294': 'TTchem-seq', 'SRR13510331': 'TTchem-seq', 'SRR13510332': 'TTchem-seq', 'SRR13510333': 'TTchem-seq', 'SRR13510334': 'TTchem-seq', 'SRR13510335': 'TTchem-seq', 'SRR13510336': 'TTchem-seq', 'SRR13510337': 'TTchem-seq', 'SRR13510338': 'TTchem-seq', 'SRR13510339': 'TTchem-seq', 'SRR13510340': 'TTchem-seq', 'SRR13510341': 'TTchem-seq', 'SRR13510342': 'TTchem-seq', 'SRR13510254': 'TTchem-seq', 'SRR13510256': 'TTchem-seq', 'SRR18248312': 'TTchem-seq', 'SRR18248316': 'TTchem-seq', 'SRR18248314': 'TTchem-seq', 'SRR18248318': 'TTchem-seq', 'SRR17038288': '4sU-seq', 'SRR17038289': '4sU-seq', 'SRR17038292': '4sU-seq', 'SRR17038293': '4sU-seq', 'SRR17038296': '4sU-seq', 'SRR17038297': '4sU-seq', 'SRR17038300': '4sU-seq', 'SRR17038301': '4sU-seq', 'SRR17038304': '4sU-seq', 'SRR17038305': '4sU-seq', 'SRR17038308': '4sU-seq', 'SRR17038309': '4sU-seq', 'SRR13510346': '4sU-seq', 'SRR13510347': '4sU-seq', 'SRR13510348': '4sU-seq', 'SRR18248916': 'RNA-seq', 'SRR18248920': 'RNA-seq', 'SRR18248924': 'RNA-seq', 'SRR18248914': 'RNA-seq', 'SRR18248918': 'RNA-seq', 'SRR18248922': 'RNA-seq', 'SRR5756320': '4sU-seq', 'SRR5756321': '4sU-seq', 'SRR5756322': '4sU-seq', 'SRR5756323': '4sU-seq', 'SRR5756324': '4sU-seq', 'SRR5756325': '4sU-seq', 'SRR5756326': '4sU-seq', 'SRR5756327': '4sU-seq', 'SRR5756344': '4sU-seq', 'SRR5756345': '4sU-seq', 'SRR5756346': '4sU-seq', 'SRR5756347': '4sU-seq', 'SRR5756348': '4sU-seq', 'SRR5756349': '4sU-seq', 'SRR5756350': '4sU-seq', 'SRR5756351': '4sU-seq', 'SRR3000786': 'm1A-seq', 'SRR3000787': 'm1A-seq', 'SRR5749642': 'RNA-seq', 'SRR5749643': 'RNA-seq', 'SRR5749644': 'RNA-seq', 'SRR5749645': 'RNA-seq', 'SRR5749646': 'RNA-seq', 'SRR5749647': 'RNA-seq'}]

In [5]:
#hash

sequencing = {'SRR8392699': 'RNA-seq', 'SRR8392700': 'RNA-seq', 'SRR8392703': 'RNA-seq', 'SRR8392704': 'RNA-seq', 'SRR8392707': 'Ribo-seq', 'SRR8392708': 'Ribo-seq', 'SRR8392711': 'Ribo-seq', 'SRR8392712': 'Ribo-seq', 'SRR2522096': 'RNA-seq', 'SRR2522099': 'RNA-seq', 'SRR2522102': 'RNA-seq', 'SRR10129832': 'RNA-seq', 'SRR13436541': 'RNA-seq', 'SRR13436542': 'RNA-seq', 'SRR13436543': 'RNA-seq', 'SRR7309387': 'RNA-seq', 'SRR9029562': 'RNA-seq', 'SRR9029564': 'RNA-seq', 'SRR9029566': 'RNA-seq', 'SRR9029563': 'MeRIP-seq', 'SRR9029565': 'MeRIP-seq', 'SRR9029567': 'MeRIP-seq', 'SRR3309259': 'RNA-seq', 'SRR3309260': 'RNA-seq', 'SRR3309261': 'RNA-seq', 'SRR7241962': 'RNA-seq', 'SRR7241963': 'RNA-seq', 'SRR7241964': 'RNA-seq', 'SRR7241965': 'RNA-seq', 'SRR7241966': 'RNA-seq', 'SRR7241967': 'RNA-seq', 'SRR7241968': 'RNA-seq', 'SRR7241969': 'RNA-seq', 'SRR7241970': 'RNA-seq', 'SRR10908166': 'RNA-seq', 'SRR10908167': 'RNA-seq', 'SRR10908168': 'RNA-seq', 'SRR10908163': 'RNA-seq', 'SRR10908164': 'RNA-seq', 'SRR10908165': 'RNA-seq', 'SRR648668': 'Ribo-seq', 'SRR648670': 'Ribo-seq', 'SRR15177493': 'm6Am-seq', 'SRR15177494': 'm6Am-seq', 'SRR15177495': 'm6Am-seq', 'SRR15177496': 'm6Am-seq', 'SRR15177497': 'm6Am-seq', 'SRR15177498': 'm6Am-seq', 'SRR15177499': 'm6Am-seq', 'SRR18302238': 'RNA-seq', 'SRR18302239': 'RNA-seq', 'SRR18302240': 'RNA-seq', 'SRR18302251': 'RNA-seq', 'SRR18302252': 'RNA-seq', 'SRR18302254': 'RNA-seq', 'SRR18302262': 'RNA-seq', 'SRR18302263': 'RNA-seq', 'SRR18302264': 'RNA-seq', 'SRR18302274': 'RNA-seq', 'SRR18302275': 'RNA-seq', 'SRR18302276': 'RNA-seq', 'SRR7359773': 'RNA-seq', 'SRR7359774': 'RNA-seq', 'SRR7359775': 'RNA-seq', 'SRR7359665': 'RNA-seq', 'SRR7359666': 'RNA-seq', 'SRR7359667': 'RNA-seq', 'SRR7359701': 'RNA-seq', 'SRR7359702': 'RNA-seq', 'SRR7359703': 'RNA-seq', 'SRR7359737': 'RNA-seq', 'SRR7359738': 'RNA-seq', 'SRR7359739': 'RNA-seq', 'SRR7359761': 'RNA-seq', 'SRR7359762': 'RNA-seq', 'SRR7359763': 'RNA-seq', 'SRR7359785': 'RNA-seq', 'SRR7359786': 'RNA-seq', 'SRR7359787': 'RNA-seq', 'SRR7359797': 'RNA-seq', 'SRR7359798': 'RNA-seq', 'SRR7359799': 'RNA-seq', 'SRR7359677': 'RNA-seq', 'SRR7359678': 'RNA-seq', 'SRR7359679': 'RNA-seq', 'SRR7359689': 'RNA-seq', 'SRR7359690': 'RNA-seq', 'SRR7359691': 'RNA-seq', 'SRR7359713': 'RNA-seq', 'SRR7359714': 'RNA-seq', 'SRR7359715': 'RNA-seq', 'SRR7359725': 'RNA-seq', 'SRR7359726': 'RNA-seq', 'SRR7359727': 'RNA-seq', 'SRR7359749': 'RNA-seq', 'SRR7359750': 'RNA-seq', 'SRR7359751': 'RNA-seq', 'SRR12926169': 'RNA-seq', 'SRR12926170': 'RNA-seq', 'SRR12926171': 'RNA-seq', 'SRR12926172': 'RNA-seq', 'SRR12926185': 'RNA-seq', 'SRR12926186': 'RNA-seq', 'SRR12926187': 'RNA-seq', 'SRR12926188': 'RNA-seq', 'SRR12926161': 'RNA-seq', 'SRR12926162': 'RNA-seq', 'SRR12926163': 'RNA-seq', 'SRR12926164': 'RNA-seq', 'SRR12926177': 'RNA-seq', 'SRR12926178': 'RNA-seq', 'SRR12926179': 'RNA-seq', 'SRR12926180': 'RNA-seq', 'SRR19077081': 'PRO-seq', 'SRR19077089': 'PRO-seq', 'SRR19077082': 'PRO-seq', 'SRR19077090': 'PRO-seq', 'SRR19077085': 'PRO-seq', 'SRR19077093': 'PRO-seq', 'SRR19077086': 'PRO-seq', 'SRR19077094': 'PRO-seq', 'SRR12801710': 'SLAM-seq', 'SRR12801711': 'SLAM-seq', 'SRR11067756': 'SLAM-seq', 'SRR11067757': 'SLAM-seq', 'SRR11067758': 'SLAM-seq', 'SRR12801712': 'SLAM-seq', 'SRR12801713': 'SLAM-seq', 'SRR12801714': 'SLAM-seq', 'SRR11067753': 'SLAM-seq', 'SRR11067754': 'SLAM-seq', 'SRR11067755': 'SLAM-seq', 'SRR16555321': 'RNA-seq', 'SRR16555322': 'RNA-seq', 'SRR16555315': 'RNA-seq', 'SRR16555316': 'RNA-seq', 'SRR16555317': 'RNA-seq', 'SRR16555318': 'RNA-seq', 'SRR17038864': 'RNA-seq', 'SRR17038865': 'RNA-seq', 'SRR17038866': 'RNA-seq', 'SRR11817840': 'RNA-seq', 'SRR11817841': 'RNA-seq', 'SRR11817842': 'RNA-seq', 'SRR11817843': 'RNA-seq', 'SRR11817844': 'RNA-seq', 'SRR11817845': 'RNA-seq', 'SRR11817852': 'RNA-seq', 'SRR11817853': 'RNA-seq', 'SRR11817854': 'RNA-seq', 'SRR11817855': 'RNA-seq', 'SRR11817856': 'RNA-seq', 'SRR11817857': 'RNA-seq', 'SRR9257619': 'RNA-seq', 'SRR9257620': 'RNA-seq', 'SRR9257621': 'RNA-seq', 'SRR9257622': 'RNA-seq', 'SRR9257623': 'RNA-seq', 'SRR9257624': 'RNA-seq', 'SRR9257625': 'RNA-seq', 'SRR9257626': 'RNA-seq', 'SRR9257627': 'RNA-seq', 'SRR9257637': 'RNA-seq', 'SRR9257638': 'RNA-seq', 'SRR9257639': 'RNA-seq', 'SRR9257640': 'RNA-seq', 'SRR9257641': 'RNA-seq', 'SRR9257642': 'RNA-seq', 'SRR9257643': 'RNA-seq', 'SRR9257644': 'RNA-seq', 'SRR9257645': 'RNA-seq', 'SRR11684069': 'RNA-seq', 'SRR11684070': 'RNA-seq', 'SRR11684071': 'RNA-seq', 'SRR11684072': 'RNA-seq', 'SRR11684073': 'RNA-seq', 'SRR11684074': 'RNA-seq', 'SRR10761036': 'RNA-seq', 'SRR10761037': 'RNA-seq', 'SRR10761038': 'RNA-seq', 'SRR1061343': 'RNA-seq', 'SRR1061344': 'RNA-seq', 'SRR11195423': 'RNA-seq', 'SRR11195425': 'RNA-seq', 'SRR11195422': 'RNA-seq', 'SRR11195424': 'RNA-seq', 'SRR11195426': 'RNA-seq', 'SRR11195427': 'RNA-seq', 'SRR11195428': 'RNA-seq', 'SRR11195429': 'RNA-seq', 'SRR11195431': 'RNA-seq', 'SRR11195433': 'RNA-seq', 'SRR11195430': 'RNA-seq', 'SRR11195432': 'RNA-seq', 'SRR8334015': 'TT-seq', 'SRR8334016': 'TT-seq', 'SRR8334017': 'TT-seq', 'SRR8334018': 'TT-seq', 'SRR8334021': 'RNA-seq', 'SRR8334022': 'RNA-seq', 'SRR8334023': 'RNA-seq', 'SRR8334024': 'RNA-seq', 'SRR8334027': 'mNET-seq', 'SRR8334028': 'mNET-seq', 'SRR8334029': 'mNET-seq', 'SRR8334030': 'mNET-seq', 'SRR8334035': 'TT-seq', 'SRR8334036': 'TT-seq', 'SRR8334037': 'TT-seq', 'SRR8334038': 'TT-seq', 'SRR10953094': 'RNA-seq', 'SRR10953095': 'RNA-seq', 'SRR10953096': 'RNA-seq', 'SRR10953097': 'RNA-seq', 'SRR10953098': 'RNA-seq', 'SRR8669175': 'PRO-seq', 'SRR8669176': 'PRO-seq', 'SRR8669177': 'PRO-seq', 'SRR8669167': 'PRO-seq', 'SRR8669168': 'PRO-seq', 'SRR8669169': 'PRO-seq', 'SRR8669170': 'PRO-seq', 'SRR8669171': 'PRO-seq', 'SRR12267715': 'PRO-seq', 'SRR12267716': 'PRO-seq', 'SRR12267717': 'PRO-seq', 'SRR12267718': 'PRO-seq', 'SRR12267719': 'PRO-seq', 'SRR12267720': 'PRO-seq', 'SRR12267721': 'PRO-seq', 'SRR12267722': 'PRO-seq', 'SRR13436390': 'RNA-seq', 'SRR13436391': 'RNA-seq', 'SRR13436392': 'RNA-seq', 'SRR13436393': 'RNA-seq', 'SRR13436394': 'RNA-seq', 'SRR13436395': 'RNA-seq', 'SRR13436396': 'RNA-seq', 'SRR13436397': 'RNA-seq', 'SRR13436398': 'RNA-seq', 'SRR13436399': 'RNA-seq', 'SRR13436400': 'RNA-seq', 'SRR13436401': 'RNA-seq', 'SRR13510258': 'TTchem-seq', 'SRR13510259': 'TTchem-seq', 'SRR13510260': 'TTchem-seq', 'SRR13510262': 'TTchem-seq', 'SRR13510263': 'TTchem-seq', 'SRR13510264': 'TTchem-seq', 'SRR13510285': 'TTchem-seq', 'SRR13510286': 'TTchem-seq', 'SRR13510287': 'TTchem-seq', 'SRR13510288': 'TTchem-seq', 'SRR13510289': 'TTchem-seq', 'SRR13510290': 'TTchem-seq', 'SRR13510291': 'TTchem-seq', 'SRR13510292': 'TTchem-seq', 'SRR13510293': 'TTchem-seq', 'SRR13510294': 'TTchem-seq', 'SRR13510331': 'TTchem-seq', 'SRR13510332': 'TTchem-seq', 'SRR13510333': 'TTchem-seq', 'SRR13510334': 'TTchem-seq', 'SRR13510335': 'TTchem-seq', 'SRR13510336': 'TTchem-seq', 'SRR13510337': 'TTchem-seq', 'SRR13510338': 'TTchem-seq', 'SRR13510339': 'TTchem-seq', 'SRR13510340': 'TTchem-seq', 'SRR13510341': 'TTchem-seq', 'SRR13510342': 'TTchem-seq', 'SRR13510254': 'TTchem-seq', 'SRR13510256': 'TTchem-seq', 'SRR18248312': 'TTchem-seq', 'SRR18248316': 'TTchem-seq', 'SRR18248314': 'TTchem-seq', 'SRR18248318': 'TTchem-seq', 'SRR17038288': '4sU-seq', 'SRR17038289': '4sU-seq', 'SRR17038292': '4sU-seq', 'SRR17038293': '4sU-seq', 'SRR17038296': '4sU-seq', 'SRR17038297': '4sU-seq', 'SRR17038300': '4sU-seq', 'SRR17038301': '4sU-seq', 'SRR17038304': '4sU-seq', 'SRR17038305': '4sU-seq', 'SRR17038308': '4sU-seq', 'SRR17038309': '4sU-seq', 'SRR13510346': '4sU-seq', 'SRR13510347': '4sU-seq', 'SRR13510348': '4sU-seq', 'SRR18248916': 'RNA-seq', 'SRR18248920': 'RNA-seq', 'SRR18248924': 'RNA-seq', 'SRR18248914': 'RNA-seq', 'SRR18248918': 'RNA-seq', 'SRR18248922': 'RNA-seq', 'SRR5756320': '4sU-seq', 'SRR5756321': '4sU-seq', 'SRR5756322': '4sU-seq', 'SRR5756323': '4sU-seq', 'SRR5756324': '4sU-seq', 'SRR5756325': '4sU-seq', 'SRR5756326': '4sU-seq', 'SRR5756327': '4sU-seq', 'SRR5756344': '4sU-seq', 'SRR5756345': '4sU-seq', 'SRR5756346': '4sU-seq', 'SRR5756347': '4sU-seq', 'SRR5756348': '4sU-seq', 'SRR5756349': '4sU-seq', 'SRR5756350': '4sU-seq', 'SRR5756351': '4sU-seq', 'SRR3000786': 'm1A-seq', 'SRR3000787': 'm1A-seq', 'SRR5749642': 'RNA-seq', 'SRR5749643': 'RNA-seq', 'SRR5749644': 'RNA-seq', 'SRR5749645': 'RNA-seq', 'SRR5749646': 'RNA-seq', 'SRR5749647': 'RNA-seq'}

In [6]:
# Conversion by specifying dictionary data to mapper using pandas.dataframe.rename

df1.rename(mapper=sequencing, axis=1, inplace= True) 
df1

,RNA-seq,RNA-seq,RNA-seq,RNA-seq,RNA-seq,RNA-seq,RNA-seq,RNA-seq,RNA-seq,RNA-seq,...,RNA-seq,RNA-seq,RNA-seq,RNA-seq,SLAM-seq,SLAM-seq,SLAM-seq,SLAM-seq,SLAM-seq,SLAM-seq
GeneName,,,,,,,,,,,,,,,,,,,,,
A1BG,0.937577,0.905060,1.173431,0.951361,1.616084,1.587653,0.839417,0.707164,0.688915,0.807707,...,0.150518,3.972351,1.388637,0.267622,1.000000,1.000000,1.000000,1.000000,1.000000,0.497684
A1CF,1.274827,1.000000,1.000000,1.000000,1.578923,1.121376,1.125679,1.256608,0.867105,0.542718,...,1.000000,1.000000,1.000000,1.000000,0.939182,1.000000,1.052121,1.029972,1.000000,1.000000
A2M,0.954195,1.510970,1.340899,0.800410,2.867888,0.271588,1.027820,0.628021,0.646622,1.000000,...,1.000000,4.285260,1.000000,1.000000,1.000000,1.000000,1.000000,0.875078,2.271058,1.530530
A2ML1,1.078959,0.649897,0.789869,1.665942,2.674006,8.028230,3.515341,9.282938,0.929338,0.266727,...,1.000000,0.795947,1.000000,1.000000,1.000000,1.000000,1.000000,2.026651,1.000000,1.000000
A3GALT2,1.000000,1.000000,1.000000,1.000000,0.924578,1.000000,1.000000,0.468382,0.600246,0.241123,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZYG11A,0.760432,0.909720,0.482176,0.646283,1.120735,2.408908,1.034067,0.755074,0.604657,0.607964,...,1.359665,0.376821,0.726672,1.000000,1.481506,2.386030,0.452458,0.905474,0.769990,0.698244
ZYG11B,0.787264,0.721801,1.000042,0.542887,1.157050,1.273877,0.872713,0.699073,0.654058,0.984260,...,1.000000,3.525577,0.732377,1.000000,1.302668,1.473649,0.801247,0.990479,1.276938,0.965806
ZYX,0.801273,0.900931,1.045951,1.061333,1.631890,1.232130,0.882310,0.693453,1.202578,2.086475,...,1.000000,22.843448,1.000000,1.000000,1.989758,3.081110,0.651634,0.973580,0.940957,0.801653
ZZEF1,0.919589,1.146141,2.152184,1.007932,2.294421,1.007538,0.986618,0.461906,1.294873,1.825901,...,1.000000,2.814540,1.262472,1.000000,1.895826,1.884423,1.012679,1.285301,1.456858,0.922310
ZZZ3,1.047701,1.043861,1.133138,0.843305,1.712004,1.156953,1.115583,0.664913,1.120227,2.973859,...,1.000000,1.000000,1.000000,1.000000,3.222935,3.395541,0.816406,1.424926,1.308535,0.989775

In [7]:
# Only 5 or 1/5 threshold (HN5)

temp = pd.DataFrame()

# Extract unique column name 
sample_list = df1.columns.unique()

for col in sample_list:  # distinct UP, DOWN, ALL from df1
    thre = df1.filter(like = col)>=5 
    temp[col + '-up' ] = thre.sum(axis=1)
    thre = df1.filter(like = col)<=1/5
    temp[col + '-down' ] = thre.sum(axis=1)
    thre = df1.filter(like = col) >= 0
    temp[col  + '-all'] = thre.sum(axis=1)

all_columns = temp.filter(regex='-all$')  #ALL pair (for check)
temp["all(check)"] = all_columns.sum(axis=1)

thre =df1>= 0  # ALL pair
temp["all"] = thre.sum(axis=1)

for word in sample_list:
    temp["unchange_" + word] = temp[word + "-all"] - temp[word + "-up"] - temp[word + "-down"] # unchnage
    temp["HN5_" + word] =  temp[word + "-up"] - temp[word + "-down"] #HN-score (threshold 5)


total_columns = temp.filter(regex='^HN5')  #Total_HN-score
temp["Total_HN-score"] = total_columns.sum(axis=1)

temp

,RNA-seq-up,RNA-seq-down,RNA-seq-all,SLAM-seq-up,SLAM-seq-down,SLAM-seq-all,TTchem-seq-up,TTchem-seq-down,TTchem-seq-all,TT-seq-up,...,HN5_m1A-seq,unchange_Ribo-seq,HN5_Ribo-seq,unchange_m6Am-seq,HN5_m6Am-seq,unchange_mNET-seq,HN5_mNET-seq,unchange_PRO-seq,HN5_PRO-seq,Total_HN-score
GeneName,,,,,,,,,,,,,,,,,,,,,
A1BG,5,3,192,0,0,11,0,0,34,0,...,1,6,0,7,0,4,0,24,0,3
A1CF,3,1,192,0,0,11,0,0,34,0,...,0,6,0,7,0,4,0,24,0,2
A2M,7,6,192,0,0,11,1,1,34,1,...,0,6,0,7,0,4,0,23,-1,1
A2ML1,6,1,192,0,0,11,1,0,34,0,...,1,6,0,7,0,4,0,22,0,11
A3GALT2,8,5,192,0,0,11,0,4,34,1,...,0,6,0,7,0,4,0,24,0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZYG11A,4,1,192,0,0,11,3,0,34,0,...,0,6,0,7,0,4,0,24,0,7
ZYG11B,4,3,192,0,0,11,0,0,34,0,...,0,6,0,7,0,4,0,24,0,1
ZYX,8,5,192,0,0,11,0,0,34,0,...,1,5,1,7,0,4,0,22,0,5
ZZEF1,6,1,192,0,0,11,0,0,34,0,...,0,6,0,7,0,4,0,23,1,6
ZZZ3,6,0,192,0,0,11,0,0,34,0,...,1,6,0,7,0,4,0,24,0,7

In [8]:
tempHN5= temp.sort_values(by= "Total_HN-score", ascending=False)
tempHN5

,RNA-seq-up,RNA-seq-down,RNA-seq-all,SLAM-seq-up,SLAM-seq-down,SLAM-seq-all,TTchem-seq-up,TTchem-seq-down,TTchem-seq-all,TT-seq-up,...,HN5_m1A-seq,unchange_Ribo-seq,HN5_Ribo-seq,unchange_m6Am-seq,HN5_m6Am-seq,unchange_mNET-seq,HN5_mNET-seq,unchange_PRO-seq,HN5_PRO-seq,Total_HN-score
GeneName,,,,,,,,,,,,,,,,,,,,,
HSPA6,156,1,192,2,0,11,32,0,34,6,...,2,4,2,0,7,2,2,15,7,245
HSPA1A,146,0,192,0,0,11,32,0,34,8,...,2,1,5,1,6,1,3,15,7,239
HSPA1B,147,0,192,0,0,11,32,0,34,8,...,2,1,3,7,0,1,3,15,7,231
DNAJB1,135,1,192,0,0,11,25,0,34,6,...,2,2,4,6,1,2,2,15,7,210
BAG3,112,1,192,1,0,11,23,0,34,6,...,2,4,2,7,0,4,0,18,6,181
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
N4BP1,2,26,192,0,0,11,0,11,34,0,...,0,6,0,7,0,4,0,24,0,-41
ZNF784,5,26,192,2,1,11,0,8,34,0,...,0,6,0,7,0,4,0,24,0,-42
TSSK3,13,40,192,2,1,11,6,9,34,1,...,1,4,0,6,-1,4,0,21,-3,-43
HRCT1,2,27,192,0,3,11,1,12,34,0,...,0,6,0,5,-2,4,0,21,-3,-52
H1-3,10,24,192,0,0,11,0,31,34,0,...,-1,4,-2,7,0,4,0,23,-1,-71

In [9]:
tempHN5.to_csv('../source/HN-score_human' + '_HN5' + '_sequencing_all.csv', sep=",")